### ISSUE TITLE
 Thank you very much for your sharing.

### ISSUE THREAD

**Issue by lgl-960709** [ai-winter/ros_motion_planning#1]
Please tell me how to debug the inconsistency between the gazebo and RVIZ maps

**Comment by ZhanyuGuo** [comment]
Hello @lgl-960709, and thanks for your supporting!

Could you provide more details on the `inconsistency between gazebo and RVIZ maps` that you are referring to?

We hope to fix any possible bugs as soon as possible, Thank you!
