### ISSUE TITLE
build.sh error

### ISSUE THREAD

**Issue by chan-yuu** [ai-winter/ros_motion_planning#104]
![image](https://github.com/user-attachments/assets/51235a9a-8589-4d0f-be81-c704ab9f31ee)

/usr/bin/ld: cannot find -losqp
/usr/bin/ld: cannot find -lunwind-ptrace
/usr/bin/ld: cannot find -lunwind-setjmp
/usr/bin/ld: cannot find -lunwind-coredump
/usr/bin/ld: cannot find -lunwind-generic
/usr/bin/ld: cannot find -lunwind
collect2: error: ld returned 1 exit status
make[2]: *** [core/controller/controller/CMakeFiles/controller.dir/build.make:122: /home/cyun/learn_ws/11/ros_motion_planning/devel/lib/libcontroller.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:7852: core/controller/controller/CMakeFiles/controller.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by chan-yuu** [comment]
1.install libunwind：
```
sudo apt install libunwind-setjmp*
sudo apt-get install libunwind-dev
```
2.install osqp:
```
git clone --recursive https://github.com/oxfordcontrol/osqp.git
cd osqp

```
```
mkdir build
cd build
cmake ..
make
sudo make install
```

`sudo ldconfig`

Re execute build.sh：
![Screenshot from 2024-12-26 01-27-42](https://github.com/user-attachments/assets/56e175e4-3a8e-44df-9e65-308649a934c2)

**Comment by ZhanyuGuo** [comment]
Thanks for your solution!

**Comment by liusumengshang** [comment]
![001](https://github.com/user-attachments/assets/566004ff-2e62-445b-aac0-cea420aa25ae)
请问这个问题怎么去解决

**Comment by chan-yuu** [comment]
`pip install rospkg`
