### ISSUE TITLE
Map not recieved

### ISSUE THREAD

**Issue by GeorgeBethel** [ai-winter/ros_motion_planning#11]
I get the error below on the terminal

[ WARN] [1683284527.630343657, 90.141000000]: No laser scan received (and thus no pose updates have been published) for 90.141000 seconds.  Verify that data is being published on the /scan topic.
[ WARN] [1683284531.473494152, 91.721000000]: Timed out waiting for transform from base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 0.1 timeout was 0.1.
[ WARN] [1683284544.047433434, 96.821000000]: Timed out waiting for transform from base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 0.1 timeout was 0.1.

I did not find anywhere you broadcast transform

**Comment by ai-winter** [comment]
Hello, @GeorgeBethel 

How did you start the environment? Checking the ROS nodes would be helpful, especially ensure that `AMCL` and `Move Base` node have been successfully executed.

**Comment by GeorgeBethel** [comment]
Hello,

Thank you for your response. I started the main.sh file. Move base and amcl
nodes are also running.

**Comment by GeorgeBethel** [comment]
Rviz view

![image](https://user-images.githubusercontent.com/60924030/236460403-09235c9c-d76d-4c25-91c8-dab4ca9c87ea.png)

**Comment by ai-winter** [comment]
@GeorgeBethel You can try to check out the tf-tree by `rqt_tf_tree` tool. The following image shows the tf-tree running normally, provided for your reference.

![frames](https://user-images.githubusercontent.com/61778098/236464724-1be91f25-7295-46a6-a748-96deed0511e1.png)

**Comment by GeorgeBethel** [comment]
Thank. It has been resolved. The issues was due to some incomplete dependencies. I uninstalled and reinstalled ROS noetic

**Comment by WeiJunREN** [comment]
> Thank. It has been resolved. The issues was due to some incomplete dependencies. I uninstalled and reinstalled ROS noetic

Hello,could you tell me what dependencies did you reinstalled ? I meet a same question , hh
