### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by yjydiancom** [ai-winter/ros_motion_planning#12]
![图片](https://github.com/ai-winter/ros_motion_planning/assets/91858119/bacecba8-745d-46b0-af39-86e7ce98accf)
Which files should I run to get the following results?

**Comment by ZhanyuGuo** [comment]
Hello @yjydiancom, and thanks for your supporting! For this issue, you should refer to `README.md`.

To get different results, you need to change the configuration in the `./src/user_config/user_config.yaml`, and options can be seen in about [line 30](https://github.com/ai-winter/ros_motion_planning/blob/9d876149b42b6ab18ef7eb8f89642c91582a6746/src/sim_env/launch/include/navigation/move_base.launch.xml#L30) of [move_base.launch.xml](https://github.com/ai-winter/ros_motion_planning/blob/9d876149b42b6ab18ef7eb8f89642c91582a6746/src/sim_env/launch/include/navigation/move_base.launch.xml).

Hope this helps.

**Comment by yjydiancom** [comment]
Okay, thank you very much. I'm learning to understand the code.
