### ISSUE TITLE
Pure Pursuit

### ISSUE THREAD

**Issue by guilyx** [ai-winter/ros_motion_planning#13]
Hi there,

If there's no ongoing development for this, I'll start implementing a Pure Pursuit algorithm (control on x thrust and yaw rate).

I also made this: https://github.com/guilyx/ros_motion_planning_docker 

To make it easier for people setup their systems with your repository.

**Comment by ai-winter** [comment]
Hello, @guilyx

Thank you very much for your support in the project. We encourage your contributions by submitting **pull requests (PRs)**, and we also welcome you to engage in technical discussions with us if necessary.
