### ISSUE TITLE
Hello, boss, I want to ask which file I should modify in which location if I want to change the algorithm

### ISSUE THREAD

**Issue by lgl-960709** [ai-winter/ros_motion_planning#2]

**Comment by ZhanyuGuo** [comment]
Hello, thanks for your support @lgl-960709.

You can simply change the algorithm in [user_config.yaml](https://github.com/ai-winter/ros_motion_planning/blob/master/src/user_config/user_config.yaml).

And, you can select the `robot1_global_planner` and `robot1_local_planner` according to [move_base.launch.xml](https://github.com/ai-winter/ros_motion_planning/blob/master/src/sim_env/launch/include/navigation/move_base.launch.xml). 
For example, `robot1_global_planner: "a_star"` and `robot1_local_planner: "dwa"`.

Feel free to ask any questions later!

**Comment by ai-winter** [comment]
`README.md` gives an example in detail, you can also refer to this configure.
```shell
map: "warehouse"
world: "warehouse"
robots_config:
  - robot1_type: "turtlebot3_burger"
    robot1_global_planner: "astar"
    robot1_local_planner: "dwa"
    robot1_x_pos: "0.0"
    robot1_y_pos: "0.0"
    robot1_z_pos: "0.0"
    robot1_yaw: "-1.57"
  - robot2_type: "turtlebot3_burger"
    robot2_global_planner: "jps"
    robot2_local_planner: "pid"
    robot2_x_pos: "-5.0"
    robot2_y_pos: "-7.5"
    robot2_z_pos: "0.0"
    robot2_yaw: "0.0"
robots_init: "robots_rviz_init.yaml"
rviz_file: "sim_env.rviz"
```

**Comment by lgl-960709** [comment]
Thank you very much for your reply. After I modified it, it can run, but there may be some problems with the robot model. At present, there are only two wheels. Wish you a happy life!



---Original---
From: "Yang ***@***.***&gt;
Date: Wed, Mar 1, 2023 18:22 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ai-winter/ros_motion_planning] Hello, boss, I want to ask whichfile I should modify in which location if I want to change the algorithm(Issue #2)




 
README.md gives an example in detail, you can also refer to this configure.
 map: "warehouse" world: "warehouse" robots_config:   - robot1_type: "turtlebot3_burger"     robot1_global_planner: "astar"     robot1_local_planner: "dwa"     robot1_x_pos: "0.0"     robot1_y_pos: "0.0"     robot1_z_pos: "0.0"     robot1_yaw: "-1.57"   - robot2_type: "turtlebot3_burger"     robot2_global_planner: "jps"     robot2_local_planner: "pid"     robot2_x_pos: "-5.0"     robot2_y_pos: "-7.5"     robot2_z_pos: "0.0"     robot2_yaw: "0.0" robots_init: "robots_rviz_init.yaml" rviz_file: "sim_env.rviz"

**Comment by ai-winter** [comment]
Hello, @lgl-960709 

Thanks for your issue. The simulation is normal in our machine. Did the terminal give any error messages? Or you could try to download model files from [turtlebot3](https://github.com/ROBOTIS-GIT/turtlebot3), then update the `urdf` and `meshes`.

**Comment by theskee-delta3** [comment]
Hello, @lgl-960709 
I can't find dijkstra src file, and how do I change algorithm to dijkstra?

**Comment by ai-winter** [comment]
Hello, @theskee-delta3 
Considering that Dijkstra's algorithm is a special case of A*, the relevant logic is integrated in the [a_star.cpp](https://github.com/ai-winter/ros_motion_planning/blob/master/src/planner/global_planner/graph_planner/src/a_star.cpp). To apply the Dijkstra's algorithm, you can just select it in `user_config.yaml`. If you have any other questions, please feel free to create a new issue.

**Comment by theskee-delta3** [comment]
> Hello, @theskee-delta3 Considering that Dijkstra's algorithm is a special case of A*, the relevant logic is integrated in the [a_star.cpp](https://github.com/ai-winter/ros_motion_planning/blob/master/src/planner/global_planner/graph_planner/src/a_star.cpp). To apply the Dijkstra's algorithm, you can just select it in `user_config.yaml`. If you have any other questions, please feel free to create a new issue.

Can you example how to change to dijkstra algorithm. I'm lost

**Comment by ZhanyuGuo** [comment]
> > Hello, @theskee-delta3 Considering that Dijkstra's algorithm is a special case of A*, the relevant logic is integrated in the [a_star.cpp](https://github.com/ai-winter/ros_motion_planning/blob/master/src/planner/global_planner/graph_planner/src/a_star.cpp). To apply the Dijkstra's algorithm, you can just select it in `user_config.yaml`. If you have any other questions, please feel free to create a new issue.
> 
> Can you example how to change to dijkstra algorithm. I'm lost

@theskee-delta3, in [user_config.yaml](https://github.com/ai-winter/ros_motion_planning/blob/master/src/user_config/user_config.yaml), you can change `robot1_global_planner` to `dijkstra`, whose options can be seen in [move_base.launch.xml](https://github.com/ai-winter/ros_motion_planning/blob/master/src/sim_env/launch/include/navigation/move_base.launch.xml).

We will improve our documentation, and we are sorry for the options here are so obscure.
