### ISSUE TITLE
是否能出一期A*融合DWA的ros 路径规划器

### ISSUE THREAD

**Issue by ZEROS-L** [ai-winter/ros_motion_planning#21]

**Comment by ai-winter** [comment]
Hello, @ZEROS-L 

You can set
```yaml
robot1_global_planner: "astar"
robot1_local_planner: "dwa"
```
in `user_config.yaml`. Then the system will combine A* with DWA automatically in move_base framework. You can also reach me via WeChat(yhd13950307060) if necessary.

**Comment by ZEROS-L** [comment]
Thanks for the reply , I'm very happy to hear from you. I was thinking the same thing before and very grateful to get confirmation from you。
