### ISSUE TITLE
can't find file

### ISSUE THREAD

**Issue by ambglh** [ai-winter/ros_motion_planning#24]
:~/ros_study/src/ros_motion_planning/src/sim_env/scripts$ ./main.sh 
RLException: [main.launch] is neither a launch file in package [sim_env] nor is [sim_env] a launch file name
The traceback for the exception was written to the log file
how can I solve this problem?

**Comment by ambglh** [comment]
I have used catkin_make
ghm@ghm:~/ros_study/src/ros_motion_planning/src/sim_env/scripts$ rospack find sim_env 
/home/ghm/ros_study/src/ros_motion_planning/src/sim_env

**Comment by zhangxu140823** [comment]
Thank you for your program!   I want to solve the problem as follow:
/ros_motion_planning/src/third_party/gazebo_plugins/pedestrian_visualizer_plugin/gazebo_ped_visualizer_plugin/include/pedestrian_visual_plugin.h:38:10: fatal error: gazebo_sfm_plugin/ped_state.h:  
not found ped_state.h

**Comment by ZhanyuGuo** [comment]
Hello @zhangxu140823, please refer to #22.

**Comment by ZhanyuGuo** [comment]
Hello @ambglh. We have tried it in a clean environment, but still not encountered this issue.

I notice that you put the code in your own ROS workspace. I think you can try moving the reposity to a new place, not sourcing other workspace (maybe in your `~/.bashrc`, e.g. `source xxx/devel/setup.bash`, comment it and open a new terminal), and following our readme again.
