### ISSUE TITLE
Non ROS-Version

### ISSUE THREAD

**Issue by NilsDengler** [ai-winter/ros_motion_planning#29]
Hi,
is it planned or possible to release a non-ROS, pure C++ version of this package?

**Comment by ai-winter** [comment]
Hello, @NilsDengler 

This repository is built based on ROS for the development of a path planning algorithm library, aiming to facilitate the rapid construction of physical simulation applications. If separated from ROS, it would not be possible to obtain an actual cost map. In such cases, you can refer to the implementations provided in [Python Version](https://github.com/ai-winter/python_motion_planning) or [Matlab Version](https://github.com/ai-winter/matlab_motion_planning) to achieve this goal.
