### ISSUE TITLE
May I ask why my program runs successfully, but the robot does not move？

### ISSUE THREAD

**Issue by TWSTYPH** [ai-winter/ros_motion_planning#4]

**Comment by TWSTYPH** [comment]
Both rviz and gazebo show the robot model normally, but the robot doesn't move

**Comment by ai-winter** [comment]
Hello, @TWSTYPH 

Thanks for your issue. Remember to check the `Nav Goal` box in `Rviz` to give your agent a navigation destination.

**Comment by WeiJunREN** [comment]
哈喽，咨询一下这个问题最后解决了嘛
