### ISSUE TITLE
Sampling-based algorithms for dynamic obstacles? :)

### ISSUE THREAD

**Issue by random-guest** [ai-winter/ros_motion_planning#45]
Thank you for sharing this great work as open source!

I was wondering whether you are planning on expanding the set of sampling-based algorithms to handle dynamic obstacles,i.e, algorithms like RT-RRT*, Am-RRT*, or Bi-AM-RRT*.

Regards,

**Comment by ai-winter** [comment]
@random-guest 

We will consider continuing to enhance the algorithm in upcoming versions. Welcome your ongoing interest in the project's progress and also encourage you to contribute code.
