### ISSUE TITLE
RRT not visible on screen

### ISSUE THREAD

**Issue by babypisellino** [ai-winter/ros_motion_planning#47]
Hi, I was trying to run the code with the RRT algorithm. I edited the file "user_config.yaml" by entering:
robot1_global_planner: "rrt"
robot1_local_planner: "pid"

The only thing that is modified besides this was the gui of gazebo.
Once I run the command on Rviz, using a 2dnav goal, I get nothing. The turtlebot starts moving but I don’t see the RRT tree on the screen. With other global planners instead I see on screen what I should get without problems.
Thanks in advance for the support

**Comment by ai-winter** [comment]
@babypisellino 

Please check if the marker data published in the `SamplePlanner/tree` topic has been checked in Rviz.

**Comment by ZhanyuGuo** [comment]
@babypisellino, like this.

![Screenshot from 2024-01-27 16-59-23](https://github.com/ai-winter/ros_motion_planning/assets/65705518/bfcd40f1-0091-42c4-9866-2fa00ce1e6dc)
