### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by robot-WT** [ai-winter/ros_motion_planning#49]
hello, I encoutered this problem, but it does not seem to affect the navigation. I am not sure if there is an unknown impact. Can you help check it out? thank you.

   File "../src/third_party/dynamic_xml_config/main_generate.py", line 20
     def __init__(self, *plugins) -> None:
                                  ^
SyntaxError: invalid syntax

**Comment by ai-winter** [comment]
@robot-WT 

Please select Python 3 to run the program. The failure of this will affect the planning algorithm switching.

**Comment by robot-WT** [comment]
yes, you are right. I can't complete the algorithm switch, but after using python3, I still have the above error.

**Comment by robot-WT** [comment]
sorry，I was careless. There was one thing I didn’t change. Thank you very much for your answer.
​
