### ISSUE TITLE
Not find packages

### ISSUE THREAD

**Issue by MyKN** [ai-winter/ros_motion_planning#51]
When make catkin_make in file, it works without any error, but some packages and files such as nav_core, global_planner or utils directory can not see connection between them. Also, any changes in user config does not  effect about changing of global and local planner. I solved this problem with using roscd and rospack for me and I wanted to let you know

**Comment by ZhanyuGuo** [comment]
Hello @MyKN, and thanks for your supporting!

I'm sorry I don't understand the problem you met and how you have fixed it. Can you provide more details?

For
> any changes in user config does not effect

, you should run [main.sh](https://github.com/ai-winter/ros_motion_planning/blob/master/scripts/main.sh) to update launch files.
