### ISSUE TITLE
How can I apply this planner to the navigation of my own robot in a real environment?

### ISSUE THREAD

**Issue by xiaoliuchongchongchong** [ai-winter/ros_motion_planning#55]
Hello, may I ask if this planner can be used for real-world scenarios instead of Gazebo simulations?

**Comment by ZhanyuGuo** [comment]
Hello @xiaoliuchongchongchong, you can refer to [this](https://github.com/ai-winter/ros_motion_planning/blob/master/docs/realworld.md).

**Comment by xiaoliuchongchongchong** [comment]
> Hello @xiaoliuchongchongchong, you can refer to [this](https://github.com/ai-winter/ros_motion_planning/blob/master/docs/realworld.md).

Thank you very much for your answer
