### ISSUE TITLE
costmap

### ISSUE THREAD

**Issue by zvemif** [ai-winter/ros_motion_planning#58]
Hello. I have been puzzled for several days. When using RRT, why can I see the costmap in Rviz simulation, but the path planning does not follow the costmap, instead, it follows the static map layer? Thank you.

**Comment by ai-winter** [comment]
@zvemif 

Please attach pictures about your questions.

**Comment by zvemif** [comment]
![Uploading aa117f50edcdb4a0fbaae97d4139aef.png…]()

**Comment by zvemif** [comment]
为什么不是按照代价地图进行规划呢？
![aa117f50edcdb4a0fbaae97d4139aef](https://github.com/ai-winter/ros_motion_planning/assets/137969244/adb3e3cc-74f1-44ed-868a-90b764a72dad)

**Comment by ai-winter** [comment]
The planned path ensures avoidance of high-cost areas; the path depicted in the figure is acceptable. Strict adherence to cost map planning may result in no feasible solutions.

**Comment by zvemif** [comment]
Thank you! Where can I set it, do I follow the high cost area or set the cost size?

**Comment by zvemif** [comment]
> The planned path ensures avoidance of high-cost areas; the path depicted in the figure is acceptable. Strict adherence to cost map planning may result in no feasible solutions.

Thank you! Where can I set up and plan according to the cost map？
