### ISSUE TITLE
你好，我想问一下是否支持多机器人的路径规划，即在rviz给出一个2D NAV GOAL，多台小车以不同的路径走到goal？目前看到框架里由multi提示，但是没有具体的指导。不知道能否指点一下操作步骤？

### ISSUE THREAD

**Issue by SYS-zdk** [ai-winter/ros_motion_planning#63]

**Comment by ai-winter** [comment]
@SYS-zdk 

The current project does not support this functionality. If customization of this feature is needed, please contact me via WeChat.
