### ISSUE TITLE
Some questions about starting points

### ISSUE THREAD

**Issue by ZengJunTao111** [ai-winter/ros_motion_planning#69]
Hi winter, I have a question. In this setvertex function, if node, when the current node is the first node, which is the starting point, does it not have a parent node, does the parent node not exist? So how is the parent node defined and handled in this function?

**Comment by ai-winter** [comment]
@ZengJunTao111 

The parent node of the starting point is set to be null. In fact, during path backtracking, the parent node of the starting point is not traversed, and the iteration is terminated at the starting point.
