### ISSUE TITLE
informed rrt算法中的c_best的bug问题

### ISSUE THREAD

**Issue by Ceg411** [ai-winter/ros_motion_planning#73]
在测试informed rrt*算法时，我想得到找到的路径长度，应该在路径更新的时候直接输出c_best的值就可以，但是通过测试发现c_best的值要比它发布的路径长度要大。在路径更新时，除了更新 c_best，我添加了根据path计算路径长度的代码，正常情况下，打印出来的
c_best和t_length应该是一样的，但结果却是前面几次打印出来的两个数值大小不一样，后面几次又都一样了。

1. 代码部分

![1](https://github.com/ai-winter/ros_motion_planning/assets/51402851/7c6b382a-6b45-42d8-b9d8-d5e3c71ae734)

2.结果输出
![2](https://github.com/ai-winter/ros_motion_planning/assets/51402851/3cdec56e-a9fa-4190-8399-9c67b2f0f0ee)

**Comment by realHarvey** [comment]
look at your loop for caculating `t_length`, the ending `i` will be `path.size()-1`, `path[i+1]` is out of range
