### ISSUE TITLE
路径平滑功能添加

### ISSUE THREAD

**Issue by xiaochoumengyan** [ai-winter/ros_motion_planning#74]
请问如何把里面的路径平滑算法应用进去啊？那些路径规划插件并没有集成路径平滑算法诶

**Comment by ai-winter** [comment]
@xiaochoumengyan 

The curve generation currently available in the package serves as the foundation for path smoothing. Algorithms for trajectory optimization will be released in **ROS Motion Planning Pro**. Feel free to contact me via WeChat or E-mail for further details.

**Comment by xiaochoumengyan** [comment]
请问什么时候能发布ros_motion_planning_pro呢？



---原始邮件---
发件人: "Yang ***@***.***&gt;
发送时间: 2024年4月28日(周日) 晚上7:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ai-winter/ros_motion_planning] 路径平滑功能添加 (Issue #74)




 
@xiaochoumengyan
 
The curve generation currently available in the package serves as the foundation for path smoothing. Algorithms for trajectory optimization will be released in ROS Motion Planning Pro. Feel free to contact me via WeChat or E-mail for further details.
