### ISSUE TITLE
曲线优化

### ISSUE THREAD

**Issue by 123345qwas** [ai-winter/ros_motion_planning#75]
请问如何将里面曲线优化的代码加进去

**Comment by bigpigdog** [comment]
@123345qwas 

包含相关头文件，实例化一个对象，调用其中的方法就可以了，但要注意函数的输入与输出类型。我现在是这么用的，算能用。

**Comment by ai-winter** [comment]
@123345qwas @bigpigdog 

We currently do not offer a direct path smoothing algorithm. This aspect can be customized, and for further requirements, my WeChat can be found on the GitHub homepage.

**Comment by bigpigdog** [comment]
@123345qwas 

我也是刚开始学习，一起进步。说实话，我不是非常清楚。全局路径规划都不是只规划一次就完事了，他也有一个更新频率。如果全局地图上出现了新的障碍物（障碍物层），那么你就会很明显的看到A*重新规划路径了。既然都叫rrt了，肯定很随机吧，哈哈哈。

**Comment by 123345qwas** [comment]
大佬的意思是说，我可以把rrt更新频率调高一点？主要是rrt它更新得太快了，走着走着路线就更新得偏差很大，出现转圈圈，摇摆之类的情况了，看着吐血
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, May 7, 2024 04:07 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [ai-winter/ros_motion_planning] 曲线优化 (Issue #75)

&nbsp;



 
@123345qwas
 
我也是刚开始学习，一起进步。说实话，我不是非常清楚。全局路径规划都不是只规划一次就完事了，他也有一个更新频率。如果全局地图上出现了新的障碍物（障碍物层），那么你就会很明显的看到A*重新规划路径了。既然都叫rrt了，肯定很随机吧，哈哈哈。
