### ISSUE TITLE
There is a little problem with map "warehouse"

### ISSUE THREAD

**Issue by JiaoxianDu** [ai-winter/ros_motion_planning#76]
When running the AMCL algorithm and the car gets close to the edge of the map, the localization drifts.
I think it's related to the commit f728f1a, and after that the pgm file didn't update in time.
Corrected map file (by slam_karto):
![image](https://github.com/ai-winter/ros_motion_planning/assets/83548820/44ef17cb-4079-44e6-880c-ec08d60f4768)
Original map file:
![image](https://github.com/ai-winter/ros_motion_planning/assets/83548820/5bfd4356-fa82-4eb0-a6c0-21776f08732a)
As you can see, the corrected map file should be a little bit more slender (like 20 cm) than the original, which is obvious when you look at the bottom of the map.

**Comment by ai-winter** [comment]
@JiaoxianDu 

Thanks for your contribution. We'll fix it later. You can also provide us with your corrected map.
