### ISSUE TITLE
Hello, thank you for sharing! May I ask how to disable the global path planning algorithm? I would like to use only the local path planning DWA algorithm for experimentation.

### ISSUE THREAD

**Issue by chengrj** [ai-winter/ros_motion_planning#8]
Hello, thank you for sharing! May I ask how to disable the global path planning algorithm? I would like to use only the local path planning DWA algorithm for experimentation.

**Comment by ai-winter** [comment]
Hello, @chengrj 

Now there is no way to disable the global path planning. We are sorry about it. However, we plan to implement a planner that publishes empty plans to meet your requirement in the future.  Welcome your continued interest in the project.

**Comment by chengrj** [comment]
May I ask if it is enough to leave the option 'robot1_global_planner' blank in the user_config.yaml file?

**Comment by chengrj** [comment]
May I ask which global path planning algorithm is combined with dwa.gif in readme.md to achieve the desired effect?

**Comment by ai-winter** [comment]
Hello, @chengrj

Setting `robot1_global_planner: ` is equivalent to disabling the global planner plugin, which will enable the default planner called `Navfn` in ROS, namely there is also a global path during navigation.

**Comment by chengrj** [comment]
Thank you for your answer! May I replace it with my own map file? How to achieve it?

**Comment by ai-winter** [comment]
Sure, @chengrj. You can achieve it by replacing `map` item in `user_config.yaml` with your own map.

**Comment by chengrj** [comment]
Thank you！
