### ISSUE TITLE
PID with model

### ISSUE THREAD

**Issue by Dennis-AIGC** [ai-winter/ros_motion_planning#88]
https://github.com/ai-winter/ros_motion_planning/blob/d0f8f569df0987e83dad79ab18e64e3f1b60c2a2/src/core/local_planner/pid_planner/src/pid_planner.cpp#L326

Hello there, how can I best understand the main points of this function?

**Comment by omigeft** [comment]
The returned value of this function is the control vector `u` that comprises two command values: `u[0]` represents the new linear velocity, and `u[1]` denotes the new angular velocity.
