### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by ZHOU363** [ai-winter/ros_motion_planning#92]
[根据readme安装conan后编译存在如下问题
![屏幕截图 2024-09-09 102942](https://github.com/user-attachments/assets/7cae079c-0010-4c78-b0ff-bb280fd5e089)

**Comment by CharlotteDucky** [comment]
进入3rd文件夹执行一下conan_install.sh就可以了，详情参考网上conan的安装、配置和使用
