### ISSUE TITLE
关于切换全局规划算法以及局部规划算法的问题

### ISSUE THREAD

**Issue by ZHOU363** [ai-winter/ros_motion_planning#97]
![屏幕截图 2024-09-29 164356](https://github.com/user-attachments/assets/c078582c-78dc-4beb-84e0-a1c4e83a8bfc)
博主您好 在切换路径规划算法过程中，已经在user_config.yaml文件中更改算法但是运行main.sh文件后显示的仍然是之前的算法
![Uploading 屏幕截图 2024-09-29 164313.png…]()

**Comment by ZHOU363** [comment]
![Uploading 屏幕截图 2024-09-29 164313.png…]()

**Comment by ai-winter** [comment]
@ZHOU363 

Please ensure that your python version is 3.x.

**Comment by ZHOU363** [comment]
python的版本为3.6
![Uploading 屏幕截图 2024-09-30 095414.png…]()

**Comment by ssl2002** [comment]
要运行main_generate.py生成新的main.launch
